/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rutins.aleks.ctrlcurve

import kotlin.test.Test
import kotlin.test.assertTrue

class PIDTest {
    @Test fun canRunPID() {
        val k = 100.0
        val tolerance = 0.01
        val initial = 0.0
        val target = 3600.0

        val final = runPID(initial, target, tolerance, k) { _, current, _, _ ->
            current + calculateCorrection()
        }

        assert(isWithinTolerance(final, target, tolerance))
    }
}
