/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.rutins.aleks.ctrlcurve;

import org.junit.jupiter.api.Test;

import com.rutins.aleks.ctrlcurve.math.Tolerance;

import static org.junit.jupiter.api.Assertions.assertEquals;

class PIDTest {
    @Test void canRunPID() {
        double k = 100.0;
        double tolerance = 1.0;
        double initial = 0.0;
        double target = 500.0;

        double finalResult = PID.runPID(initial, target, tolerance, k, k, k, (pid, _initial, current, _target, error) -> {
            double result = current + pid.calculateCorrection();
            return result;
        });

        assertEquals(true, Tolerance.isWithinTolerance(finalResult, target, tolerance));
    }
}
